apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-aws
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:     
  serviceAccountTemplate:
    metadata:
      annotations:
        eks.amazonaws.com/role-arn: {{ .Values.globals.crossplaneIAMRole }}
---


apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-ec2
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  package: xpkg.crossplane.io/crossplane-contrib/provider-aws-ec2:v1.21.1
  runtimeConfigRef:
    apiVersion: pkg.crossplane.io/v1beta1
    kind: DeploymentRuntimeConfig
    name: provider-aws

---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-eks
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  package: xpkg.crossplane.io/crossplane-contrib/provider-aws-eks:v1.21.1
  runtimeConfigRef:
    apiVersion: pkg.crossplane.io/v1beta1
    kind: DeploymentRuntimeConfig
    name: provider-aws

---

apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-iam
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  package: xpkg.crossplane.io/crossplane-contrib/provider-aws-iam:v1.21.1
  runtimeConfigRef:
    apiVersion: pkg.crossplane.io/v1beta1
    kind: DeploymentRuntimeConfig
    name: provider-aws

---

apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: provider-aws
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  credentials:
    source: IRSA